"""
Main entry point for acct-automation.

Subcommands:
  generate   Regenerate pre_prompt.md from the template and lib/ introspection.
  list       Show available task scripts.
  run        Execute a task script by name.

Usage:
    python main.py generate
    python main.py list
    python main.py run extract_attachments
    python main.py run dump_emails --after-date 2025-06-01
"""

import argparse
import importlib
import importlib.util
import inspect
import pkgutil
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
LIB_ROOT = PROJECT_ROOT / "lib"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
TEMPLATE_PATH = PROJECT_ROOT / "pre_prompt_template.md"
OUTPUT_PATH = PROJECT_ROOT / "pre_prompt.md"

# Ensure project root is on sys.path for script imports
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Lib introspection
# ---------------------------------------------------------------------------

def get_module_summary(module) -> list[str]:
    """Return one-line summaries for each public callable in a module."""
    lines = []
    all_names = getattr(module, "__all__", None)
    members = inspect.getmembers(module)

    for name, obj in members:
        if name.startswith("_"):
            continue
        if all_names and name not in all_names:
            continue
        if not (inspect.isfunction(obj) or inspect.isclass(obj)):
            continue

        sig = ""
        try:
            sig = str(inspect.signature(obj))
        except (ValueError, TypeError):
            pass

        doc = inspect.getdoc(obj)
        short_doc = doc.split("\n")[0] if doc else ""

        kind = "class" if inspect.isclass(obj) else "fn"
        lines.append(f"  {kind} {name}{sig}  # {short_doc}" if short_doc else f"  {kind} {name}{sig}")

    return lines


def generate_lib_listing() -> str:
    """Walk lib/ and produce a token-efficient listing of available modules."""
    output_lines = ["## Available lib/ modules", ""]

    for _importer, modname, _ispkg in pkgutil.walk_packages(
        path=[str(LIB_ROOT)], prefix="lib."
    ):
        if "__pycache__" in modname or modname.split(".")[-1].startswith("_"):
            continue

        try:
            module = importlib.import_module(modname)
        except Exception:
            continue

        mod_doc = inspect.getdoc(module)
        short_mod_doc = mod_doc.split("\n")[0] if mod_doc else ""

        header = f"### {modname}"
        if short_mod_doc:
            header += f"  — {short_mod_doc}"
        output_lines.append(header)

        members = get_module_summary(module)
        if members:
            output_lines.append("```")
            output_lines.extend(members)
            output_lines.append("```")

        output_lines.append("")

    return "\n".join(output_lines)


def generate_scripts_listing() -> str:
    """List available task scripts with their one-line descriptions."""
    output_lines = ["## Available task scripts (scripts/)", ""]
    output_lines.append("| Script | Description |")
    output_lines.append("|--------|-------------|")

    for script_path in sorted(SCRIPTS_DIR.glob("*.py")):
        if script_path.name.startswith("_"):
            continue

        description = ""
        try:
            source = script_path.read_text(encoding="utf-8")
            if source.startswith('"""') or source.startswith("'''"):
                quote = source[:3]
                end = source.find(quote, 3)
                if end != -1:
                    doc = source[3:end].strip()
                    description = doc.split("\n")[0]
        except Exception:
            pass

        name = script_path.stem
        output_lines.append(f"| `{name}` | {description} |")

    output_lines.append("")
    output_lines.append("Run with: `python main.py run <script_name>`")
    output_lines.append("")
    return "\n".join(output_lines)


# ---------------------------------------------------------------------------
# Pre-prompt generation
# ---------------------------------------------------------------------------

def generate_pre_prompt() -> str:
    """Build the full pre_prompt.md content from template + introspected data."""
    lib_listing = generate_lib_listing()
    scripts_listing = generate_scripts_listing()

    if TEMPLATE_PATH.exists():
        template = TEMPLATE_PATH.read_text(encoding="utf-8")
    else:
        template = _default_template()

    content = template.replace("{{LIB_LISTING}}", lib_listing)
    content = content.replace("{{SCRIPTS_LISTING}}", scripts_listing)
    return content


def _default_template() -> str:
    return """# acct-automation — Pre-prompt Reference

This document is auto-generated by `main.py generate`.

---

{{SCRIPTS_LISTING}}

---

{{LIB_LISTING}}
"""


# ---------------------------------------------------------------------------
# Subcommand handlers
# ---------------------------------------------------------------------------

def cmd_generate(args):
    """Generate pre_prompt.md and write it to disk."""
    content = generate_pre_prompt()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated: {OUTPUT_PATH}")


def get_available_scripts() -> list[str]:
    """Return script names (without .py) from the scripts/ directory."""
    return sorted(
        p.stem for p in SCRIPTS_DIR.glob("*.py")
        if not p.name.startswith("_")
    )


def _get_script_info(script_path: Path) -> dict:
    """Extract description and argparse arguments from a script file."""
    info = {"name": script_path.stem, "description": "", "args": [], "default_task": ""}

    try:
        source = script_path.read_text(encoding="utf-8")
    except Exception:
        return info

    # Extract module docstring (first line)
    if source.startswith('"""') or source.startswith("'''"):
        quote = source[:3]
        end = source.find(quote, 3)
        if end != -1:
            doc = source[3:end].strip()
            info["description"] = doc.split("\n")[0]

    # Extract argparse add_argument calls (explicit flags)
    import re
    for match in re.finditer(
        r'add_argument\(\s*["\'](-{1,2}[\w-]+)["\'].*?help\s*=\s*["\']([^"\']+)["\']',
        source,
        re.DOTALL,
    ):
        flag, help_text = match.group(1), match.group(2)
        info["args"].append(f"{flag}: {help_text}")

    # Detect parse_task_args usage and extract default_task
    task_match = re.search(
        r'parse_task_args\(.*?default_task\s*=\s*["\'](\w+)["\']',
        source,
        re.DOTALL,
    )
    if task_match:
        info["default_task"] = task_match.group(1)

    return info


def cmd_list(args):
    """Print available task scripts with descriptions and arguments."""
    print("Available task scripts:\n")

    for script_path in sorted(SCRIPTS_DIR.glob("*.py")):
        if script_path.name.startswith("_"):
            continue

        info = _get_script_info(script_path)
        print(f"  {info['name']}")
        if info["description"]:
            print(f"    {info['description']}")
        if info["default_task"]:
            print(f"    Task config: tasks/{info['default_task']}.yml (override with --task)")
            print(f"    Config values are passable as CLI args (use --help for details)")
        if info["args"]:
            print(f"    Extra args: {', '.join(info['args'])}")
        print()


def _load_script_module(script_name: str):
    """Dynamically load a script module from scripts/ directory."""
    script_path = SCRIPTS_DIR / f"{script_name}.py"
    if not script_path.exists():
        return None

    spec = importlib.util.spec_from_file_location(
        f"scripts.{script_name}", str(script_path)
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _get_script_entry_function(module, script_name: str):
    """Get the main entry function from a script module (matches script name)."""
    # Try exact match first
    func = getattr(module, script_name, None)
    if func and callable(func):
        return func

    # Fallback: find any public function that takes a single 'config' arg
    for name, obj in inspect.getmembers(module, inspect.isfunction):
        if name.startswith("_"):
            continue
        sig = inspect.signature(obj)
        params = list(sig.parameters.keys())
        if params == ["config"]:
            return obj

    return None


def _run_script(script_name: str, argv: list = None):
    """Load and run a script by name, passing argv for parse_task_args."""
    if argv:
        sys.argv = [f"scripts/{script_name}.py"] + argv
    else:
        sys.argv = [f"scripts/{script_name}.py"]

    module = _load_script_module(script_name)
    if module is None:
        available = ", ".join(get_available_scripts())
        print(f"Error: script '{script_name}' not found in scripts/")
        print(f"Available: {available}")
        sys.exit(1)

    entry_fn = _get_script_entry_function(module, script_name)
    if entry_fn is None:
        print(f"Error: no entry function found in scripts/{script_name}.py")
        sys.exit(1)

    # parse_task_args is called inside the module's __main__ block,
    # but since we're importing, we call it explicitly
    from lib.task_config import parse_task_args

    # Find the parse_task_args call parameters from the module
    # Look for description and default_task in the module source
    description = ""
    default_task = script_name

    # Try to extract from module docstring
    if module.__doc__:
        description = module.__doc__.strip().split("\n")[0]

    # Call parse_task_args to get config (handles GUI + CLI)
    config = parse_task_args(
        description=description or script_name.replace("_", " ").title(),
        default_task=default_task,
        argv=argv,
    )

    # Invoke the entry function
    entry_fn(config)


def cmd_run(args):
    """Run a task script by name, or list available scripts if none specified."""
    if args.script is None:
        cmd_list(args)
        return

    script_name = args.script
    if not (SCRIPTS_DIR / f"{script_name}.py").exists():
        available = ", ".join(get_available_scripts())
        print(f"Error: script '{script_name}' not found in scripts/")
        print(f"Available: {available}")
        sys.exit(1)

    _run_script(script_name, args.script_args or [])


# ---------------------------------------------------------------------------
# Git operations
# ---------------------------------------------------------------------------

def cmd_commit(args):
    """Stage all changes and commit with a summary + file list."""
    from lib.git_ops import get_repo, stage_all, commit, get_changed_files

    repo = get_repo()

    # Check for changes
    changed = get_changed_files(repo)
    if not changed:
        print("Nothing to commit — working tree is clean.")
        return

    # Stage all changes
    stage_all(repo)

    # Get or prompt for summary
    summary = args.message
    if not summary:
        print("Changed files:")
        for f in changed:
            print(f"  - {f}")
        print()
        summary = input("Commit summary (max 80 chars): ").strip()
        if not summary:
            print("Aborted — no summary provided.")
            sys.exit(1)

    if len(summary) > 80:
        print(f"Warning: summary truncated to 80 chars.")
        summary = summary[:80]

    sha = commit(repo, summary)
    print(f"Committed: {sha[:8]} {summary}")


def cmd_push(args):
    """Push the current branch to remote."""
    from lib.git_ops import get_repo, push

    repo = get_repo()
    remote = args.remote or "origin"
    branch = args.branch or repo.head.shorthand

    print(f"Pushing {branch} to {remote}...")
    try:
        push(repo, remote_name=remote, branch=branch)
        print("Done.")
    except Exception as e:
        print(f"Push failed: {e}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# CLI (argparse)
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="main.py",
        description="acct-automation CLI — generate docs or run task scripts.",
    )
    subparsers = parser.add_subparsers(dest="command")

    # generate
    sp_generate = subparsers.add_parser(
        "generate",
        help="Regenerate pre_prompt.md from template and lib/ introspection.",
    )
    sp_generate.set_defaults(func=cmd_generate)

    # list
    sp_list = subparsers.add_parser(
        "list",
        help="Show available task scripts in scripts/.",
    )
    sp_list.set_defaults(func=cmd_list)

    # run
    sp_run = subparsers.add_parser(
        "run",
        help="Execute a task script by name. If no script specified, lists available scripts.",
    )
    sp_run.add_argument(
        "script",
        nargs="?",
        default=None,
        help="Name of the script to run (without .py extension).",
    )
    sp_run.add_argument(
        "script_args",
        nargs=argparse.REMAINDER,
        help="Additional arguments passed through to the script.",
    )
    sp_run.set_defaults(func=cmd_run)

    # commit
    sp_commit = subparsers.add_parser(
        "commit",
        help="Stage all changes and commit with a summary + auto-generated file list.",
    )
    sp_commit.add_argument(
        "-m", "--message",
        default=None,
        help="Commit summary (max 80 chars). If omitted, will prompt interactively.",
    )
    sp_commit.set_defaults(func=cmd_commit)

    # push
    sp_push = subparsers.add_parser(
        "push",
        help="Push the current branch to a remote.",
    )
    sp_push.add_argument(
        "--remote",
        default=None,
        help="Remote name (default: origin).",
    )
    sp_push.add_argument(
        "--branch",
        default=None,
        help="Branch to push (default: current branch).",
    )
    sp_push.set_defaults(func=cmd_push)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    if args.command is None:
        # Default action: open GUI task selector
        from lib.gui_config import gui_select_task
        selected = gui_select_task()
        if selected is None:
            print("No task selected.")
            sys.exit(0)
        _run_script(selected)
    else:
        args.func(args)


if __name__ == "__main__":
    main()
